[package]
name = "rustpass"
version = "0.1.0"
authors = ["Dominik Trippel <dominik-trippel@arcor.de>"]
edition = "2018"

[dependencies]
clap = "~2.27.0"
dirs = "2.0.1"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.1.4"
rpassword = "3.0.2"
rust-crypto = "^0.2"
getrandom = "0.1"
